"""followers2

Revision ID: 44797208f19f
Revises: faff9f024e03
Create Date: 2024-03-17 19:45:49.620338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44797208f19f'
down_revision = 'faff9f024e03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('Title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Title', sa.VARCHAR(length=120), nullable=True))

    op.create_table('feedback',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
