"""feedback table

Revision ID: 50a64ef02ecc
Revises: 8f1656eeaeed
Create Date: 2024-03-18 11:49:26.149924

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50a64ef02ecc'
down_revision = '8f1656eeaeed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Rating', sa.Integer(), nullable=False),
    sa.Column('Rating_reason', sa.String(length=1024), nullable=False),
    sa.Column('Suggestions', sa.String(length=1024), nullable=False),
    sa.Column('Submitted', sa.DateTime(), nullable=False),
    sa.Column('Responsee_id', sa.Integer(), nullable=False),
    sa.Column('Feedback_project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['Feedback_project_id'], ['project.id'], ),
    sa.ForeignKeyConstraint(['Responsee_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feedback_Feedback_project_id'), ['Feedback_project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_Responsee_id'), ['Responsee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_feedback_Submitted'), ['Submitted'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feedback_Submitted'))
        batch_op.drop_index(batch_op.f('ix_feedback_Responsee_id'))
        batch_op.drop_index(batch_op.f('ix_feedback_Feedback_project_id'))

    op.drop_table('feedback')
    # ### end Alembic commands ###
