"""Add Photos to project table

Revision ID: 5374da42a659
Revises: 4613b2d45b62
Create Date: 2024-03-20 14:14:03.156204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5374da42a659'
down_revision = '4613b2d45b62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Coverphoto', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('Photo1_url', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('Photo2_url', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('Photo3_url', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('Plan', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('Plan')
        batch_op.drop_column('Photo3_url')
        batch_op.drop_column('Photo2_url')
        batch_op.drop_column('Photo1_url')
        batch_op.drop_column('Coverphoto')

    # ### end Alembic commands ###
