"""user type in user model

Revision ID: 61203e6d1067
Revises: ed530f3bdfbb
Create Date: 2024-03-14 22:16:14.421985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61203e6d1067'
down_revision = 'ed530f3bdfbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Type', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('Type')

    # ### end Alembic commands ###
