"""projects table

Revision ID: 801879bfdd69
Revises: 1e615fa54973
Create Date: 2024-03-13 12:46:47.426820

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801879bfdd69'
down_revision = '1e615fa54973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Title', sa.String(length=256), nullable=False),
    sa.Column('Timestamp', sa.DateTime(), nullable=False),
    sa.Column('User_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['User_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_Timestamp'), ['Timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_User_id'), ['User_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_User_id'))
        batch_op.drop_index(batch_op.f('ix_project_Timestamp'))

    op.drop_table('project')
    # ### end Alembic commands ###
