"""project updates

Revision ID: 8f1656eeaeed
Revises: dbdebe8fbd38
Create Date: 2024-03-17 20:58:49.279952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8f1656eeaeed'
down_revision = 'dbdebe8fbd38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('County', sa.String(length=100), nullable=True))
        batch_op.alter_column('Description',
               existing_type=sa.VARCHAR(length=140),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('Proposal',
               existing_type=sa.VARCHAR(length=1024),
               type_=sa.String(length=2048),
               existing_nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Job_title', sa.String(length=120), nullable=True))
        batch_op.drop_column('Title')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Title', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_column('Job_title')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('Proposal',
               existing_type=sa.String(length=2048),
               type_=sa.VARCHAR(length=1024),
               existing_nullable=True)
        batch_op.alter_column('Description',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=140),
               existing_nullable=True)
        batch_op.drop_column('County')

    # ### end Alembic commands ###
