"""new fields in project n user  model

Revision ID: a61e3a68d282
Revises: e3a3bd1f577a
Create Date: 2024-03-15 18:15:53.225224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a61e3a68d282'
down_revision = 'e3a3bd1f577a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Latitude', sa.Float(precision=20), nullable=True))
        batch_op.add_column(sa.Column('Longitude', sa.Float(precision=20), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Type', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('Type')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('Longitude')
        batch_op.drop_column('Latitude')

    # ### end Alembic commands ###
