"""no_followers

Revision ID: dbdebe8fbd38
Revises: 44797208f19f
Create Date: 2024-03-17 19:50:16.043997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbdebe8fbd38'
down_revision = '44797208f19f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Deadline', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('SDGs', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('Category', sa.String(length=100), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Title', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('Title')

    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('Category')
        batch_op.drop_column('SDGs')
        batch_op.drop_column('Deadline')

    # ### end Alembic commands ###
