"""empty message

Revision ID: e3a3bd1f577a
Revises: 61203e6d1067
Create Date: 2024-03-15 17:13:36.855990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3a3bd1f577a'
down_revision = '61203e6d1067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Description', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('Background', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('Proposal', sa.String(length=1024), nullable=True))
        batch_op.add_column(sa.Column('Phase', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('Phase')
        batch_op.drop_column('Proposal')
        batch_op.drop_column('Background')
        batch_op.drop_column('Description')

    # ### end Alembic commands ###
