"""new fields in user model

Revision ID: ed530f3bdfbb
Revises: 09c0b023793e
Create Date: 2024-03-14 20:05:18.802521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ed530f3bdfbb'
down_revision = '09c0b023793e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('About_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('Last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('Last_seen')
        batch_op.drop_column('About_me')

    # ### end Alembic commands ###
